// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Even.Persistence.OracleManaged")]
[assembly: AssemblyProductAttribute("Even.Persistence.Oracle")]
[assembly: AssemblyDescriptionAttribute("Oracle based persistent extensions for Even.")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
